defaults:
  - _default

name: hecp

params:
  file_paths: /root/autodl-tmp/Halloc/ebding40k/val/vlm_instruct/qwen2_5_mrg, /root/autodl-tmp/Halloc/ebding40k/val/vlm_vqa/qwen2_5_mrg, /root/autodl-tmp/Halloc/ebding40k/val/vlm_caption/qwen2_5_mrg
  all_flag: true